version: '2'
services:
  cassandra:
    container_name: cassandra_spec
    build: ./cassandra
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
  mysql:
    container_name: mysql_spec
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spec_check
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    tty: true
